# Generated by Django 4.2.18 on 2025-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(),
        ),
    ]
